### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by limeiyan1** [nanyang24/music-vue#1]
music-vue/build/webpack.dev.conf.js这个文件夹里面的  // webpack内置的devServer，设置 before()     before(app) {}里面的app是哪里来的？？

**Comment by nanyang24** [comment]
https://doc.webpack-china.org/configuration/dev-server/#devserver-before

webpack 配置的 before 和 after 是为了让 webpack-dev-server 具有服务端职能
参数 app 就是调用中间件的方法。所谓“中间件（middleware），就是处理HTTP请求的函数
https://github.com/webpack/webpack-dev-middleware
